name: Build Assets and Update Projects (main)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Inject access token in .npmrc
        run: | 
          echo "registry=https://npm.pkg.github.com/helsingborg-stad" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .

          # Check if there are any staged changes
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: build assets"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.WHITESPACE_DEVOPS_REPO_PAT }}

  update_repos:
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        repo:
          - whitespace-se/eslov.se-2024
          - whitespace-se/hoor.se-2024
          - whitespace-se/kriswebb.malmstad.se-2024
          - whitespace-se/demo1.malmstad.se-2024
          - whitespace-se/demo2.malmstad.se-2024
          - whitespace-se/trelleborg.se-2024
          - whitespace-se/arvidsjaur.se
    steps:
      - name: Checkout ${{ matrix.repo }} repo
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
          path: repo_${{ matrix.repo }}
          token: ${{ secrets.WHITESPACE_DEVOPS_REPO_PAT }}

      - name: Run Composer Update
        working-directory: repo_${{ matrix.repo }}/wordpress
        env:
          COMPOSER_AUTH: |
            {
              "github-oauth": {
                "github.com": "${{ secrets.COMPOSER_AUTH_TOKEN }}"
              },
              "http-basic": {
                "composer.whitespace.house": {
                  "username": "${{ secrets.COMPOSER_REPO_USERNAME }}",
                  "password": "${{ secrets.COMPOSER_REPO_PASSWORD }}"
                }
              }
            }
        run: composer update municipio-lts/wp-theme-municipio-2024

      - name: Delete remote branch if it exists
        working-directory: repo_${{ matrix.repo }}/wordpress
        run: |
          if git ls-remote --exit-code --heads origin update/wp-theme-municipio-2024; then
            git push origin --delete update/wp-theme-municipio-2024
          fi

      - name: Commit Composer changes and push new branch
        working-directory: repo_${{ matrix.repo }}/wordpress
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git checkout -b update/wp-theme-municipio-2024
          git add .
          git commit -m "${{ github.event.head_commit.message }}"
          git push --set-upstream origin update/wp-theme-municipio-2024
        env:
          GITHUB_TOKEN: ${{ secrets.WHITESPACE_DEVOPS_REPO_PAT }}
